//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinaQueryAppEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramProfile
    {
        public ProgramProfile()
        {
            this.QueryMains = new HashSet<QueryMain>();
            this.CourseProfiles = new HashSet<CourseProfile>();
        }
    
        public int Id { get; set; }
        public string ProgramTitle { get; set; }
        public string ProgramDescription { get; set; }
        public Nullable<bool> ProgramDiscontinued { get; set; }
    
        public virtual ICollection<QueryMain> QueryMains { get; set; }
        public virtual ICollection<CourseProfile> CourseProfiles { get; set; }
    }
}
