//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinaQueryAppEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qualification
    {
        public Qualification()
        {
            this.QueryMains = new HashSet<QueryMain>();
        }
    
        public int Id { get; set; }
        public string QualificationTitle { get; set; }
    
        public virtual ICollection<QueryMain> QueryMains { get; set; }
    }
}
