//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinaQueryAppEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueryMain
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> QueryDate { get; set; }
        public string PersonName { get; set; }
        public string FatherName { get; set; }
        public string EmailAddress { get; set; }
        public string CellNo { get; set; }
        public string LandLineNo { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Grade { get; set; }
        public string Organization { get; set; }
        public string Designation { get; set; }
        public Nullable<int> QualificationId { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> QueryTypeId { get; set; }
        public Nullable<int> QueryUser { get; set; }
        public string QueryComment { get; set; }
    
        public virtual ProgramProfile ProgramProfile { get; set; }
        public virtual Qualification Qualification { get; set; }
        public virtual QueryCategory QueryCategory { get; set; }
        public virtual QueryType QueryType { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual CourseProfile CourseProfile { get; set; }
    }
}
