//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinaQueryAppEntity.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class sinaDbEnt : DbContext
    {
        public sinaDbEnt()
            : base("name=sinaDbEnt")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ProgramProfile> ProgramProfiles { get; set; }
        public DbSet<Qualification> Qualifications { get; set; }
        public DbSet<QueryCategory> QueryCategories { get; set; }
        public DbSet<QueryMain> QueryMains { get; set; }
        public DbSet<QueryType> QueryTypes { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<CourseProfile> CourseProfiles { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual ObjectResult<WEB_SP_FindQueryByAny_Result> WEB_SP_FindQueryByAny(string queryFilter)
        {
            var queryFilterParameter = queryFilter != null ?
                new ObjectParameter("QueryFilter", queryFilter) :
                new ObjectParameter("QueryFilter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_SP_FindQueryByAny_Result>("WEB_SP_FindQueryByAny", queryFilterParameter);
        }
    }
}
